'use client';
import {useState} from 'react';
import {useApp} from './provider';
import {Field,Select,Textarea,Toggle,AsyncButton} from './ui';
import {supabase} from '@/lib/supabase';
import type {Card,EventConfig} from '@/lib/types';
export function ConfigEditor({section}:{section:string}){const {state,act,demo,notify}=useApp();const [c,setC]=useState<EventConfig>(structuredClone(state.config));const patch=(key:keyof EventConfig,value:unknown)=>setC(prev=>({...prev,[key]:value}));const text=(key:keyof EventConfig,label:string,type='text')=><Field key={key} label={label} type={type} value={String(c[key]??'')} onChange={e=>patch(key,type==='number'?Number(e.target.value):e.target.value)}/>;const area=(key:keyof EventConfig,label:string)=><Textarea key={key} label={label} value={String(c[key])} onChange={e=>patch(key,e.target.value)}/>;const cards=(key:'objectives'|'benefits'|'steps'|'rules'|'nav',label:string)=><CardList label={label} value={c[key]} onChange={v=>patch(key,v)}/>;
async function upload(key:keyof EventConfig,file:File|undefined){if(!file)return;try{if(!['image/png','image/jpeg','image/webp','image/gif','image/x-icon','image/vnd.microsoft.icon'].includes(file.type)||file.size>5*1024*1024)throw Error('Use a PNG, JPEG, WebP, GIF, or ICO image under 5 MB.');if(demo){const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});patch(key,data);}else {if(!supabase)throw Error('Connect Supabase first.');const path=crypto.randomUUID()+'.'+file.name.split('.').pop();const {error}=await supabase.storage.from('event-assets').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;patch(key,supabase.storage.from('event-assets').getPublicUrl(path).data.publicUrl);}notify('Image ready. Save changes to publish it.');}catch(e){notify(e instanceof Error?e.message:'Upload failed.');}}
const asset=(key:keyof EventConfig,label:string)=><div className="asset-field" key={key}>{text(key,label+' URL')}<label className="field"><span>Upload {label.toLowerCase()}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/x-icon" onChange={e=>void upload(key,e.target.files?.[0])}/></label>{c[key]&&<img src={String(c[key])} className="asset-preview" alt={label+' preview'}/>}</div>;
return <div className="stack"><div className="card"><h2>{section} settings</h2><p>Changes go live when you save. Content lists can be edited, reordered, hidden, or removed.</p>
{section==='Home'&&<><div className="form-grid">{text('name','Event name')}{text('logo_name','Logo name')}{text('tagline','Tagline')}{text('college','College / festival label')}{text('register_label','Register button text')}{text('explore_label','Explore button text')}{text('browser_title','Browser title')}</div>{area('description','Hero description')}{asset('logo_url','Logo')}{asset('hero_image','Hero image')}{asset('favicon','Favicon')}{asset('banner','Registration banner')}{cards('nav','Navigation - description is the section anchor: home, about, levels, rules') }<h3>Countdown</h3><Toggle label="Show countdown" value={c.countdown} onChange={v=>patch('countdown',v)}/>{text('starts_at','Event start (ISO 8601 with timezone)')}<Select label="After countdown" options={['EVENT IS LIVE','hide','EVENT COMPLETED']} value={c.after_countdown} onChange={e=>patch('after_countdown',e.target.value)}/></>}
{section==='About'&&<>{area('about_title','Section title')}{area('about','Description')}{cards('objectives','Objectives')}</>}
{section==='Why participate'&&cards('benefits','Why participate cards')}
{section==='How it works'&&cards('steps','Journey steps')}
{section==='Rules'&&cards('rules','Rule categories')}
{section==='Design'&&<><Select label="Public website theme" value={c.theme} options={['dark','light']} onChange={e=>patch('theme',e.target.value)}/><p>Light mode supplies a light background and dark text. Color overrides below apply to dark mode. Student preferences are independent.</p><div className="color-grid">{Object.entries(c.colors).map(([key,value])=><Field key={key} label={key} type="color" value={value} onChange={e=>patch('colors',{...c.colors,[key]:e.target.value})}/>)}</div><div className="form-grid"><Select label="Heading font" value={c.heading_font} options={['Arial','Georgia','Verdana','Trebuchet MS','monospace']} onChange={e=>patch('heading_font',e.target.value)}/><Select label="Body font" value={c.body_font} options={['Arial','Georgia','Verdana','Trebuchet MS','monospace']} onChange={e=>patch('body_font',e.target.value)}/>{text('radius','Button / card radius (px)','number')}<Select label="Button hover" value={c.button_hover} options={['lift','scale','none']} onChange={e=>patch('button_hover',e.target.value)}/><Select label="Button style" value={c.button_style} options={['solid','outline']} onChange={e=>patch('button_style',e.target.value)}/><Select label="Button size" value={c.button_size} options={['normal','large']} onChange={e=>patch('button_size',e.target.value)}/></div></>}
{section==='Event settings'&&<><div className="form-grid">{text('name','Event name')}{text('edition','Edition / team ID prefix')}{text('college','College / festival')}{text('venue','Venue')}{text('starts_at','Event start - ISO time')}{text('timezone','Display timezone (IANA)')}{text('checkin_open','Check-in opens - ISO time')}{text('checkin_close','Check-in closes - ISO time')}{text('results_time','Planned results time - ISO time')}</div><p>Use timestamps such as 2026-10-25T10:00:00+05:30. Schedules are informational; level timers begin only when you press Start.</p>{c.level_starts.map((v,i)=><Field key={i} label={'Level '+(i+1)+' scheduled start - ISO time'} value={v} onChange={e=>patch('level_starts',c.level_starts.map((x,j)=>j===i?e.target.value:x))}/>)}<Select label="Leaderboard visibility" options={['hidden','admin','public','after-results']} value={c.leaderboard} onChange={e=>patch('leaderboard',e.target.value)}/><Select label="Tie-break level priority after total score" value={c.tiebreak.join(',')} options={['3,2,1','3,1,2','2,3,1','2,1,3','1,3,2','1,2,3']} onChange={e=>patch('tiebreak',e.target.value.split(',').map(Number))}/><p>Changing the tie-break order is blocked while results are published.</p></>}
{section==='Registration'&&<><Toggle label="Registration open" value={c.registration_open} onChange={v=>patch('registration_open',v)}/><div className="form-grid">{text('opens_at','Registration opens - ISO time')}{text('deadline','Registration deadline - ISO time')}{text('capacity','Maximum teams','number')}</div><p>Exactly 2 members. The database always enforces the opening date, deadline, and capacity. {state.team_count} teams registered; {Math.max(0,c.capacity-state.team_count)} spots remaining.</p></>}
</div><div className="sticky-save"><AsyncButton run={async()=>{for(const k of ['starts_at','opens_at','deadline','checkin_open','checkin_close','results_time'] as const)if(!Number.isFinite(Date.parse(c[k])))throw Error('Use a valid timestamp for '+k);try{new Intl.DateTimeFormat('en',{timeZone:c.timezone}).format();}catch{throw Error('Use a valid IANA timezone.');}if(c.capacity<1||c.radius<0||c.radius>40)throw Error('Capacity must be positive; radius must be 0 to 40.');await act('save_config',{config:c});}}>Save changes</AsyncButton><a className="text-button" href="/" target="_blank" rel="noreferrer">Preview website ↗</a></div></div>;}
function CardList({label,value,onChange}:{label:string;value:Card[];onChange:(v:Card[])=>void}){const patch=(i:number,k:keyof Card,v:unknown)=>onChange(value.map((x,j)=>j===i?{...x,[k]:v}:x));const move=(i:number,step:number)=>{const next=[...value];const j=i+step;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];onChange(next);};return <div className="card-list"><h3>{label}</h3>{value.map((x,i)=><div className="editor-item" key={i}><div className="form-grid"><Field label="Title" value={x.title} onChange={e=>patch(i,'title',e.target.value)}/><Select label="Icon" value={x.icon} options={['Brain','Users','Timer','Target','Trophy','Zap','Sparkles']} onChange={e=>patch(i,'icon',e.target.value)}/></div><Textarea label="Description / content" value={x.description} onChange={e=>patch(i,'description',e.target.value)}/><div className="actions"><Toggle label="Visible" value={x.visible} onChange={v=>patch(i,'visible',v)}/><button className="button secondary small" disabled={i===0} onClick={()=>move(i,-1)}>Move up</button><button className="button secondary small" disabled={i===value.length-1} onClick={()=>move(i,1)}>Move down</button><button className="button secondary small" onClick={()=>onChange(value.filter((_,j)=>i!==j))}>Remove</button></div></div>)}<button className="button secondary" onClick={()=>onChange([...value,{title:'New item',description:'',icon:'Sparkles',visible:true}])}>+ Add item</button></div>;}